// apps/reactapp/src/app/app.tsx
import styles from './app.module.scss';

export function App() {
  const title = 'reactapp';
  return (
    <div className={styles.app}>
      <main>
        <div>
          <div style={{ textAlign: 'center' }}>
            <ui-greeting title={title} />

            <img
              width="300"
              src="https://raw.githubusercontent.com/nrwl/nx/master/images/nx-logo.png"
            />
          </div>

          <p>
            This is a React app built with <a href="https://nx.dev">Nx</a>.
          </p>
        </div>
      </main>
    </div>
  );
}

export default App;

// apps/angularapp/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'nx-angular-react-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'angularapp';
}

<div style="text-align:center">
  <ui-greeting [title]="title"></ui-greeting>
  <img
    width="300"
    src="https://raw.githubusercontent.com/nrwl/nx/master/images/nx-logo.png"
    alt="Nx - Smart, Extensible Build Framework"
  />
</div>

<p>This is an Angular app built with <a href="https://nx.dev">Nx</a>.</p>
